export * from "./dashboard";
export * from "./events";
export * from "./gallery";
export * from "./Login";
export * from "./NotFound";
export * from "./registrations";
export * from "./settings";
export * from "./team";
export * from "./urls";
